AllCops:
  TargetRubyVersion: 3.0

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'lib/ot/text_operation.rb'

Style/SelfAssignment:
  Exclude:
    - 'lib/ot/text_operation.rb'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/IfUnlessModifier:
  Exclude:
    - 'lib/ot/text_operation.rb'

Layout/LineLength:
  Enabled: false

Lint/MissingCopEnableDirective:
  Exclude:
    - 'lib/ot/text_operation.rb'

Metrics:
  Enabled: false

Naming:
  Exclude:
    - 'lib/ot/text_operation.rb'

Naming/FileName:
  AllowedAcronyms:
    - OT
  Exclude:
    - 'lib/ot-rb.rb'
